In [ ]:
##Matrix operations

##Matrices use -> AI, ML, ;

##A@B = dot product

##A*B = element wise mul

##Trnspose

##Inverse nd determinnt

##Eigenvues nd eigenvectors

##rng = rndom number generator

##seed

##Normaal Gaussian Distribution

##normal

##uniform

##shuffle

##choice

##

In [2]:
import pandas as pd
print(pd.__version__)
import numpy as np

2.3.3


In [5]:
##Student marks analysis system

students = np.array(["Anmol", "Rahul", "Priya", "Sneha", "Amit"])

subjects = np.array(["Math", "Science", "English", "Computer"])

marks = np.array([
    [85, 90, 78, 88],
    [70, 65, 80, 75],
    [95, 92, 89, 96],
    [60, 72, 68, 70],
    [88, 84, 91, 86]
])

print(students)
print(subjects)
print(marks)

['Anmol' 'Rahul' 'Priya' 'Sneha' 'Amit']
['Math' 'Science' 'English' 'Computer']
[[85 90 78 88]
 [70 65 80 75]
 [95 92 89 96]
 [60 72 68 70]
 [88 84 91 86]]


In [6]:
##Average mrs per student

avg_marks = np.mean(marks, axis=1)

print("Average Marks per Student:")
for i in range(len(students)):
    print(students[i], ":", avg_marks[i])

Average Marks per Student:
Anmol : 85.25
Rahul : 72.5
Priya : 93.0
Sneha : 67.5
Amit : 87.25


In [14]:
highest = np.max(marks, axis=1)
lowest = np.min(marks, axis=1)

print("Highest and Lowest Marks:")
for i in range(len(students)):
    print(students[i], "Highest =", highest[i], "Lowest =", lowest[i])

Highest and Lowest Marks:
Anmol Highest = 90 Lowest = 78
Rahul Highest = 80 Lowest = 65
Priya Highest = 96 Lowest = 89
Sneha Highest = 72 Lowest = 60
Amit Highest = 91 Lowest = 84


In [15]:
##Standard deviation

std_dev = np.std(marks, axis=1)

print("Average Marks per Student:")
for i in range(len(students)):
    print(students[i], ":", std_dev[i])

Average Marks per Student:
Anmol : 4.548351349665063
Rahul : 5.5901699437494745
Priya : 2.7386127875258306
Sneha : 4.55521678957215
Amit : 2.5860201081971503


In [7]:
##Ranking students



rank = np.argsort(avg_marks)[::-1]

print("\nStudent Ranking:")
for i in range(len(rank)):
    print(i + 1, ".", students[rank[i]], "-", round(avg_marks[rank[i]], 2))


Student Ranking:
1 . Priya - 93.0
2 . Amit - 87.25
3 . Anmol - 85.25
4 . Rahul - 72.5
5 . Sneha - 67.5


In [19]:
##Top students above average

class_avg = np.mean(avg_marks)

print("Class Average:", round(class_avg, 2))

print("Students Above Class Average:")
for i in range(len(students)):
    if avg_marks[i] > class_avg:
        print(students[i], "-", round(avg_marks[i], 2))


Class Average: 81.1
Students Above Class Average:
Anmol - 85.25
Priya - 93.0
Amit - 87.25


In [16]:
##Subject-wise Analysis

subject_avg = np.mean(marks, axis=0)

print("Subject-wise Average:")
for i in range(len(subjects)):
    print(subjects[i], ":", round(subject_avg[i], 2))

Subject-wise Average:
Math : 79.6
Science : 80.6
English : 81.2
Computer : 83.0


In [20]:
##Percentage Calculation

total_marks = np.sum(marks, axis=1)
percentage = total_marks / 400 * 100

print("Percentage:")
for i in range(len(students)):
    print(students[i], ":", round(percentage[i], 2), "%")

Percentage:
Anmol : 85.25 %
Rahul : 72.5 %
Priya : 93.0 %
Sneha : 67.5 %
Amit : 87.25 %


In [18]:
##Visualization-Ready Data

visual_data = np.column_stack((students, percentage))

print("Visualization Ready Data:")
print(visual_data)


Visualization Ready Data:
[['Anmol' '85.25']
 ['Rahul' '72.5']
 ['Priya' '93.0']
 ['Sneha' '67.5']
 ['Amit' '87.25']]
