In [ ]:
##Numpy

##Advantages over python lists

##Data types in array

##Reshaping arrays

In [1]:
import numpy as np

print(np.__version__)

2.3.4


In [2]:
##create array

a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
##Creating 2D ARRAY

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


In [8]:
##Creating 3D array

c = np.array([[[1, 2, 3], [4, 5, 6]], [[7,8,9], [7,8,9]]])
print(c)
print(c.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]]]
3


In [14]:
##Other arry cretion

d = np.zeros((2,3))
print(d)

e = np.ones((3, 4))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
a = np.array([1, 2, 3])
print(a)
print(a.dtype)

[1 2 3]
int64


In [22]:
b = np.array([1, 2, 3], dtype = np.float32)
print(b)
print(b.dtype)

[1. 2. 3.]
float32


In [23]:
c = a.astype(np.float64)
print(c)
print(c.dtype) 

[1. 2. 3.]
float64


In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)  # rows and columns
print(arr.ndim)   # number of dimensions
print(arr.size)   # total number of elements
print(arr.dtype)  # datatypes

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [30]:
##Reshaping arrays

a = np.arange(12)
print(a)
b = a.reshape(3,4)
print(b)

c = a.reshape(2, -1)
print(c)
print(c.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [31]:
##Flatening arrays

arr = np.array([[1, 2, 3], [3,4,5]])
print(arr)
print(arr.flatten())   ##return a copy
print(arr.ravel())     ##return a view when possible

[[1 2 3]
 [3 4 5]]
[1 2 3 3 4 5]
[1 2 3 3 4 5]


In [36]:
##Arithmetic operations

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print(a+b)   ##Addition
print(a-b)   ##Subtraction
print(a*b)   ##Mutipication
print(a/b)   ##Division
print(a%b)   ##Moduus
print(a**2)  ##Exponent

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]
[ 100  400  900 1600]


In [38]:
##Comparison operators

a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

print(a>b)
print(a==b)
print(a<=2)

[False False  True  True]
[False False False False]
[ True  True False False]


In [41]:
##Universa functions

#ufunc


a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,2))
print(np.mod(a,b))
print(np.abs(np.array([-1,-2,-3])))

[5 5 5 5]
[-3 -1  1  3]
[4 6 6 4]
[0.25       0.66666667 1.5        4.        ]
[ 1  4  9 16]
[1 2 1 0]
[1 2 3]


In [44]:
a = np.array([10,20,30,40])
print(a[0])
print(a[3])

b = np.array([[10, 20, 30], [40,50, 60]])
print(b[1,2])

10
40
60


In [47]:
##slicing

a = np.array([10, 20, 30, 40, 50])
print(a[1:4])
print(a[:3])
print(a[2:])


[20 30 40]
[10 20 30]
[30 40 50]


In [49]:
a = np.arange(10)
print(a[::2])
print(a[1:8:2])
print(a[::-1])

[0 2 4 6 8]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [51]:
##Fancy indexing  aand boolean return a copy

a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
idx = [0, 2, 7]
print(a[idx])

[10 30 80]


In [52]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
mask = a > 18
print(mask)
print(a[mask])


[False False  True  True  True  True  True]
[20 25 30 35 40]


In [55]:
##Mthemtical functions

b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(b)
print(np.sum(b))
print(np.mean(b))
print(np.median(b))
print(np.std(b))
print(np.var(b))
print(np.mean(b))
print(np.max(b))
print(np.percentile(b, 75))
print(np.sqrt(b))
print(np.log(b))
print(np.exp(b))
print(np.sin(b))

[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
5.5
2.8722813232690143
8.25
5.5
10
7.75
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]


In [59]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a)
print(b)
print(np.concatenate([a, b]))
print(np.vstack([a,b]))
print(np.hstack([a, b]))
print(np.stack([a, b], axis = 0)) 

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [64]:
a = np.arange(10)
print(a)
print(np.split(a,2))

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [63]:
a = np.array([1, 2, 3])
print(a)

print(np.append(a, [4, 5]))
print(a)

##insert

print(np.insert(a, 1, 99))
print(a)

[1 2 3]
[1 2 3 4 5]
[1 2 3]
[ 1 99  2  3]
[1 2 3]


In [68]:
##sort unique, reverse  -> do not modify the original array

##Broadcating ->   

##Advantages

##Avoids explicit loops - faster and more readable
##Avoids creating unnecessary intermediate copies of data
##Makes codes that works across scalars, vectors and matrices uniform


matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
row_add = np.array([10, 20, 30])
print(row_add)
print(matrix+row_add)

[[1 2 3]
 [4 5 6]]
[10 20 30]
[[11 22 33]
 [14 25 36]]
